service {
    proto-fd-max 15000
    cluster-name merkle-dev
}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3100
    }

    heartbeat {
        mode multicast
        multicast-group 239.1.99.222
        port 9918
        interval 150
        timeout 10
    }

    fabric {
        port 3101
    }

    info {
        port 3103
    }
}

namespace merkle {
    replication-factor 1
    default-ttl 0
    nsup-period 120
    storage-engine memory {
        data-size 4G
    }
}
